openapi: 3.1.0
info:
  title: Mock API
  version: 1.0.0
servers:
  - url: http://localhost:{port}/{basePath}
    description: The production API server
    variables:
      port:
        enum:
          - "3030"
        default: "3030"
      basePath:
        default: v2
paths:
  /example:
    get:
      summary: Example GET endpoint
      x-delay-ms: 200
      responses:
        200:
          description: Example GET response
          content:
            application/json:
              example:
                message: "This is a GET response"
  /example2:
    get:
      summary: Example GET endpoint2
      x-delay-ms: 400
      responses:
        200:
          description: Example GET response2
          content:
            application/json:
              example:
                message: "This is a GET response2"
