services:
  example:
    path: "/v2/models/example/infer"
    delay: 1200
    response: "config/response.json"
  other-example:
    path: "/v2/models/other-example/infer"
    delay: 800
    response: "config/response.json"
  health:
    path: "/v2/health/ready"
    delay: 1
    response: "config/health.json"
